// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function EnsureOriginalBackup() {
  return window['go']['main']['App']['EnsureOriginalBackup']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetBackupList() {
  return window['go']['main']['App']['GetBackupList']();
}

export function GetCurrentMachineID() {
  return window['go']['main']['App']['GetCurrentMachineID']();
}

export function GetCurrentProvider() {
  return window['go']['main']['App']['GetCurrentProvider']();
}

export function GetCurrentUsageInfo() {
  return window['go']['main']['App']['GetCurrentUsageInfo']();
}

export function GetDetectedKiroInstallPath() {
  return window['go']['main']['App']['GetDetectedKiroInstallPath']();
}

export function GetDetectedKiroVersion() {
  return window['go']['main']['App']['GetDetectedKiroVersion']();
}

export function GetKiroProcesses() {
  return window['go']['main']['App']['GetKiroProcesses']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSoftResetStatus() {
  return window['go']['main']['App']['GetSoftResetStatus']();
}

export function IsKiroRunning() {
  return window['go']['main']['App']['IsKiroRunning']();
}

export function OpenExtensionFolder() {
  return window['go']['main']['App']['OpenExtensionFolder']();
}

export function OpenMachineIDFolder() {
  return window['go']['main']['App']['OpenMachineIDFolder']();
}

export function OpenSSOCacheFolder() {
  return window['go']['main']['App']['OpenSSOCacheFolder']();
}

export function RefreshBackupUsage(arg1) {
  return window['go']['main']['App']['RefreshBackupUsage'](arg1);
}

export function RepatchExtension() {
  return window['go']['main']['App']['RepatchExtension']();
}

export function RestoreSoftReset() {
  return window['go']['main']['App']['RestoreSoftReset']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SoftResetToNewMachine() {
  return window['go']['main']['App']['SoftResetToNewMachine']();
}

export function SwitchToBackup(arg1) {
  return window['go']['main']['App']['SwitchToBackup'](arg1);
}

export function UnpatchExtension() {
  return window['go']['main']['App']['UnpatchExtension']();
}
