// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {kiroprocess} from '../models';

export function CreateBackup(arg1:string):Promise<main.Result>;

export function CreateSnapshotFromOAuth(arg1:string,arg2:main.OAuthLoginResult):Promise<main.Result>;

export function DeleteBackup(arg1:string):Promise<main.Result>;

export function EnsureOriginalBackup():Promise<main.Result>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetBackupList():Promise<Array<main.BackupItem>>;

export function GetCurrentEnvironmentName():Promise<string>;

export function GetCurrentMachineID():Promise<string>;

export function GetCurrentProvider():Promise<string>;

export function GetCurrentUsageInfo():Promise<main.CurrentUsageInfo>;

export function GetDetectedKiroInstallPath():Promise<main.Result>;

export function GetDetectedKiroVersion():Promise<main.Result>;

export function GetKiroInstallPathWithStatus():Promise<main.PathDetectionResult>;

export function GetKiroProcesses():Promise<Array<kiroprocess.ProcessInfo>>;

export function GetSettings():Promise<main.AppSettings>;

export function GetSoftResetStatus():Promise<main.SoftResetStatus>;

export function GetWindowSize():Promise<main.WindowSize>;

export function IsDeepLinkSupported():Promise<boolean>;

export function IsKiroRunning():Promise<boolean>;

export function OpenExtensionFolder():Promise<main.Result>;

export function OpenMachineIDFolder():Promise<main.Result>;

export function OpenSSOCacheFolder():Promise<main.Result>;

export function RefreshBackupUsage(arg1:string):Promise<main.UsageCacheResult>;

export function RegenerateMachineID(arg1:string):Promise<main.Result>;

export function RepatchExtension():Promise<main.Result>;

export function RestoreSoftReset():Promise<main.Result>;

export function SaveSettings(arg1:main.AppSettings):Promise<main.Result>;

export function SaveWindowSize(arg1:number,arg2:number):Promise<main.Result>;

export function SoftResetToNewMachine():Promise<main.Result>;

export function StartIdCLogin():Promise<main.OAuthLoginResult>;

export function StartSocialLogin(arg1:string):Promise<main.OAuthLoginResult>;

export function SwitchToBackup(arg1:string):Promise<main.Result>;

export function UnpatchExtension():Promise<main.Result>;

export function ValidateSnapshotName(arg1:string):Promise<main.Result>;
